### ISSUE TITLE
feature request: add user region to tags.txt

### ISSUE THREAD

**Issue by bbouldin** [chrisGerken/gramar#10]
In the generated snippets/tags.txt, it would be nice to have a userRegion to preserve edits made to the file.

**Comment by bbouldin** [comment]
it would also be nice to see sample values for each attribute (e.g. known replacements)

**Comment by chrisGerken** [comment]
What kinds of changes specifically do you want to keep?  Do you use snippets.txt as a clipboard for more complex, gramar-specific tags?

**Comment by bbouldin** [comment]
Chris,

Yes, to keep my own notes, sample values, etc., and combinations of tags or xpath expressions I use often (I know, I know, I should make a separate Token for those (but sometimes I don't for whatever reason, or I go back and do it at a later time)).

Anyway, It's a nice-to-havem, and not a huge deal if you'd rather not add that support.

-bb

**Comment by chrisGerken** [comment]
Ought to be working in latest updateSite on gramar.org/eclipse/xaa
