### ISSUE TITLE
Skip generation when target file exists and is identical

### ISSUE THREAD

**Issue by bbouldin** [chrisGerken/gramar#6]
It would be nice to avoid re-generation, even if generation is a bit slower, in the case that the target file already exists and has identical contents. IDEs that scan the directory tree would spend less time reloading & recompiling the re-generated code.

**Comment by elder4p** [comment]
+1. My experience with JET found that reading an existing file off of disk was way less expensive than writing it. So the overhead of reading was soon compensated for by the savings of not rewriting.

**Comment by chrisGerken** [comment]
This is best performed on a file store by file store basis as some file stores won't benefit from this feature.  Having said that, this is working for local file store and eclipse file store.
